# Generated by Django 3.2.14 on 2022-07-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('photo', models.CharField(max_length=150)),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=32)),
                ('photo', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='skill_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skills'),
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('jop_cost', models.IntegerField(default='enter the cost of this job')),
                ('service_providers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceprovider')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
