# Generated by Django 3.2.14 on 2022-07-29 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_serviceprovider_skill_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='skills',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='list_of_skills', to='users.skills'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_owner', to='users.serviceprovider'),
        ),
    ]
