# Generated by Django 3.2.14 on 2022-07-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_skills_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderHasSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='jop_cost',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
